# Generated by Django 5.1.4 on 2025-01-05 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('Men', 'Men'), ('Woman', 'Woman')], default='Men', max_length=6, null=True),
        ),
    ]
