# Generated by Django 5.1.4 on 2025-01-06 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_gender'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fitnessgoal',
            options={'ordering': ['-start_date'], 'verbose_name_plural': 'Fitness Goals'},
        ),
    ]
