# Generated by Django 5.1.4 on 2025-01-06 16:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_fitnessgoal_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fitnessgoal',
            options={'verbose_name_plural': 'Fitness Goals'},
        ),
        migrations.AlterField(
            model_name='fitnessgoal',
            name='start_date',
            field=models.DateField(default=datetime.date.today, help_text='Start date of the goal'),
        ),
    ]
