# Generated by Django 5.1.4 on 2025-01-08 15:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exercises', '0002_alter_exercise_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(help_text='Title of the workout plan', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Details about the workout plan')),
                ('difficulty_level', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], max_length=20)),
                ('workout_banner', models.ImageField(default='workout_banners/no-img-banner.jpg', upload_to='workout_banners/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Workout Plans',
            },
        ),
        migrations.CreateModel(
            name='WorkoutExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1, help_text='Order of the exercise in the workout plan')),
                ('repetitions', models.PositiveIntegerField(default=0, help_text='Number of repetitions for this exercise')),
                ('sets', models.PositiveIntegerField(default=0, help_text='Number of sets for this exercise')),
                ('rest_time', models.DurationField(blank=True, help_text='Rest time after completing this exercise', null=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_exercises', to='exercises.exercise')),
                ('workout_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_exercises', to='workout_management.workoutplan')),
            ],
            options={
                'verbose_name_plural': 'Workout Exercises',
                'unique_together': {('workout_plan', 'exercise', 'order')},
            },
        ),
    ]
