# Generated by Django 5.1.4 on 2025-01-08 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutplan',
            name='workout_banner',
            field=models.ImageField(blank=True, default='workout_banners/no-img-banner.jpg', null=True, upload_to='workout_banners/'),
        ),
    ]
