# Generated by Django 5.1.4 on 2025-01-09 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout_management', '0002_alter_workoutplan_workout_banner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workoutexercise',
            options={'ordering': ['order'], 'verbose_name_plural': 'Workout Exercises'},
        ),
    ]
