# Generated by Django 5.1.4 on 2025-01-11 09:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_management', '0004_workoutplan_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutplan',
            name='tags',
            field=models.JSONField(blank=True, choices=[('Weight Loss', 'Weight Loss'), ('Strength Building', 'Strength Building'), ('Cardiovascular Fitness', 'Cardiovascular Fitness'), ('Flexibility', 'Flexibility'), ('BodyBuilding', 'BodyBuilding')], default=list, help_text="Tags describing the plan, e.g., ['strength', 'weight_loss']", null=True, validators=[django.core.validators.MinLengthValidator(1, 'You must provide at least one tag.')]),
        ),
    ]
