# Generated by Django 5.1.4 on 2025-01-11 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_management', '0005_alter_workoutplan_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutplan',
            name='tags',
            field=models.JSONField(blank=True, choices=[('Weight Loss', 'Weight Loss'), ('Strength Building', 'Strength Building'), ('Cardiovascular Fitness', 'Cardiovascular Fitness'), ('Flexibility', 'Flexibility'), ('BodyBuilding', 'BodyBuilding')], default=list, help_text="Tags describing the plan, e.g., ['strength', 'weight_loss']", null=True),
        ),
    ]
