# Generated by Django 5.1.4 on 2025-01-11 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workout_management', '0005_alter_workoutplan_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoalWorkoutMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_type', models.CharField(choices=[('Weight Loss', 'Weight Loss'), ('Strength Building', 'Strength Building'), ('Cardiovascular Fitness', 'Cardiovascular Fitness'), ('Flexibility', 'Flexibility'), ('BodyBuilding', 'BodyBuilding')], max_length=35)),
                ('workout_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout_management.workoutplan')),
            ],
        ),
    ]
