# Generated by Django 5.1.4 on 2025-01-07 17:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('unique_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('description', models.TextField(help_text='Additional details about the exercise')),
                ('category', models.CharField(choices=[('Strength', 'Strength'), ('Cardio', 'Cardio'), ('Yoga', 'Yoga'), ('Flexibility', 'Flexibility'), ('Calisthenics', 'Calisthenics'), ('Aerobic', 'Aerobic')], help_text='Type of exercise', max_length=50)),
                ('equipment', models.JSONField(default=list)),
                ('repetitions', models.PositiveIntegerField(default=0)),
                ('sets', models.PositiveIntegerField(default=0)),
                ('muscle_group', models.CharField(max_length=50)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_exercises', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Exercises',
            },
        ),
    ]
